// Auto-generated from editor_data.json - DO NOT EDIT BY HAND.
#pragma once
struct MoveEntry { int id; const char* name; };

static const MoveEntry g_dribbleMoves[] = {
    { 0, "Heel Lift" },
    { 1, "South American Dribble" },
    { 2, "Straight Line Dribble" },
    { 3, "Forced Feint" },
    { 4, "Delicate Touch" },
    { 5, "Feinting Dribble" },
    { 6, "Wild Eagle Dribble" },
    { 7, "Magnificent Dribble" },
    { 8, "Rolling Dribble" },
    { 9, "Flying Squirrel Jump" },
    { 10, "Monkey Guard" },
    { 11, "Falcon Dribble" },
    { 12, "Low Falcon Dribble" },
    { 13, "Dump Truck Dribble" },
    { 14, "Acrobatic Dribble" },
    { 15, "Kaiser Dribble" },
    { 16, "Hedgehog Dribble" },
    { 17, "Magic Jump" },
    { 18, "Étoile Roulette" },
    { 19, "Beautiful Step" },
    { 20, "Kluivoort Turn" },
    { 21, "Crown Lifting" },
    { 22, "Santana Turn" },
    { 23, "Forward Somersault Dribble" },
    { 24, "High-Speed South American Dribble" },
    { 25, "Senghor Dance" },
    { 26, "Flores Dribble" },
    { 27, "Blake Dribble" },
    { 28, "Aurora Feint" },
    { 29, "Mirage Chapeau" },
    { 30, "Dynamic Feint" },
    { 31, "Muay Thai Dribble" },
    { 32, "Jumping Knee" },
    { 33, "Overhead Lift" },
    { 34, "Right-Angle Feint" },
    { 35, "Splendid Step" },
    { 36, "Leo Feint" },
    { 37, "Back Friends" },
    { 38, "Changeup Dribble" },
    { 39, "Panther Accel" },
    { 40, "Under Step" },
    { 41, "Fake Under" },
    { 42, "Rolling Chapeau" },
    { 43, "Low-Altitude Lift" },
    { 44, "Heavy Tank Dribble" },
    { 45, "Return Leg" },
    { 46, "Spring Step" },
    { 47, "Secret Passage" },
    { 48, "Roulette Spin" },
    { 49, "Spear Dribble" },
    { 50, "Carry Step" },
    { 300, "Heel Lift [Lite]" },
    { 301, "South American Dribble [Lite]" },
    { 302, "Straight Line Dribble [Lite]" },
    { 304, "Delicate Touch [Lite]" },
    { 306, "Wild Eagle Dribble [Lite]" },
    { 307, "Magnificent Dribble [Lite]" },
    { 311, "Sonic Dribble" },
    { 312, "Up-Tempo Dance" },
    { 313, "Powerful Push" },
    { 314, "Acrobatic Dribble [Lite]" },
    { 315, "Assault Dribble" },
    { 316, "Stoop Dribble" },
    { 317, "Spin Light Jump" },
    { 318, "Étoile Roulette [Lite]" },
    { 319, "Beautiful Step [Lite]" },
    { 320, "Great Fake" },
    { 321, "Trick Lifting" },
    { 348, "Swindler's Lifting" },
    { 322, "Muay Thai Dribble [Lite]" },
    { 323, "Forward Somersault Dribble [Lite]" },
    { 324, "High-Speed South American Dribble [Lite]" },
    { 325, "Up-Tempo Dance [Lite]" },
    { 326, "Flores Dribble [Lite]" },
    { 327, "Smash Dribble" },
    { 329, "Mirage Chapeau [Lite]" },
    { 330, "Dynamic Feint [Lite]" },
    { 332, "Jumping Knee [Lite]" },
    { 347, "Secret Passage [Lite]" },
    { 900, "Accel Dribble" },
    { 901, "Aerial Dribble" },
    { 902, "High-Speed Dribble" },
    { 903, "Fake Kick" },
    { 904, "Gear Change" },
    { 905, "Double Touch" },
    { 906, "Power Dribble" },
    { 907, "Megaton Dribble" },
    { 908, "Buster Dribble" },
    { 909, "Back Road" },
    { 910, "Step Over" },
    { 911, "Shield Bash" },
    { 912, "Matador Trick" },
};
static const int g_dribbleMoves_count = 92;

static const MoveEntry g_tackleMoves[] = {
    { 0, "Feinting Tackle" },
    { 1, "Power Defense" },
    { 2, "Razor Tackle" },
    { 3, "Shark Tackle" },
    { 4, "Kaiser Charge" },
    { 5, "Hedgehog Charge" },
    { 6, "Arrow Tackle" },
    { 7, "Upper Tackle" },
    { 8, "Spear Tackle" },
    { 9, "Solid Tackle" },
    { 10, "Cross Sliding" },
    { 11, "Double Leg Tackle" },
    { 12, "Screen Cut" },
    { 13, "Emperor's Cut" },
    { 14, "Blake Tackle" },
    { 15, "Aurora Curtain" },
    { 16, "Junguang Sliding" },
    { 17, "Rainbow Tackle" },
    { 18, "Muay Thai Tackle" },
    { 19, "Push Steal" },
    { 20, "Right-Angle Defense" },
    { 21, "Up-Tempo Cut" },
    { 22, "Open Charge" },
    { 23, "Biting Tackle" },
    { 24, "Arm Banker" },
    { 25, "Cool Steal" },
    { 26, "Muay Thai Sweep" },
    { 27, "Shadow Steal" },
    { 28, "Danger Spin" },
    { 29, "Sliding Header" },
    { 30, "Roll Sweeper" },
    { 31, "Sharp Steal" },
    { 301, "Power Defense [Lite]" },
    { 302, "Sharpness Cut" },
    { 303, "Brave Tackle" },
    { 304, "Riser Charge" },
    { 305, "Squat Charge" },
    { 306, "Arrow Tackle [Lite]" },
    { 307, "Upper Tackle [Lite]" },
    { 309, "Solid Tackle [Lite]" },
    { 310, "Cross Sliding [Lite]" },
    { 312, "Screen Cut [Lite]" },
    { 313, "Emperor's Cut [Lite]" },
    { 314, "Blow Tackle" },
    { 316, "Junguang Sliding [Lite]" },
    { 317, "Rainbow Tackle [Lite]" },
    { 318, "Combat Tackle" },
    { 322, "Open Charge [Lite]" },
    { 900, "Shoulder Charge" },
    { 901, "Powerful Charge" },
    { 902, "High-Speed Shoulder Charge" },
    { 903, "Hyper Charge" },
    { 904, "Paralyze Charge" },
    { 905, "Sliding" },
    { 906, "Sharp Sliding" },
    { 907, "Skillful Sliding" },
    { 908, "Forced Tackle" },
    { 909, "Desperate Sliding" },
    { 910, "Full Body Tackle" },
    { 911, "Raging Wave Tackle" },
    { 912, "Scythe Cut" },
    { 913, "Spinning Cut" },
    { 914, "Megaton Tackle" },
};
static const int g_tackleMoves_count = 63;

static const MoveEntry g_shotMoves[] = {
    { 0, "Drive Shot" },
    { 1, "Tiger Shot" },
    { 2, "Picturesque Shot" },
    { 3, "Eagle Shot" },
    { 4, "Slice Shot" },
    { 5, "Falcon Shot" },
    { 6, "Razor Shot" },
    { 7, "Fire Shot" },
    { 8, "Hedgehog Shot" },
    { 9, "Magic Shot" },
    { 10, "Slider Shot" },
    { 11, "Cannon Shot" },
    { 12, "Stinger Shot" },
    { 13, "Accel Shot" },
    { 14, "Sagittarius Shot" },
    { 15, "Sacred Shot" },
    { 16, "Diaz-Style Drive Shot" },
    { 17, "Panther Shot" },
    { 18, "Knuckle Shot" },
    { 19, "Vulture Shot" },
    { 20, "Analyze Shot" },
    { 21, "Blake Shot" },
    { 22, "Needle Shot" },
    { 23, "Sandstorm Shot" },
    { 24, "Wild Shot" },
    { 25, "Trick Shot" },
    { 27, "Dragon Shot" },
    { 28, "Acrobatic Hoop" },
    { 29, "Blast Force" },
    { 30, "Windfall" },
    { 31, "Biting Shot" },
    { 32, "Fake Shot" },
    { 33, "Sand Mirage Shot" },
    { 34, "Vulcan Cannon" },
    { 35, "Vanishing Shot" },
    { 36, "Panzer Shot" },
    { 37, "Sunset Shot" },
    { 38, "Radiant Shot" },
    { 41, "Rock Blaster" },
    { 300, "Drive Shot [Lite]" },
    { 301, "Tiger Shot [Lite]" },
    { 302, "Picturesque Shot [Lite]" },
    { 303, "Field Shot" },
    { 304, "Slice Shot [Lite]" },
    { 306, "Spinning Shot" },
    { 307, "Fire Shot [Lite]" },
    { 310, "Slider Shot [Lite]" },
    { 353, "Cannon Shot [Lite]" },
    { 311, "Rising Bazooka" },
    { 313, "Accel Shot [Lite]" },
    { 314, "Sagittarius Shot [Lite]" },
    { 315, "Sacred Shot [Lite]" },
    { 316, "Diaz-Style Drive Shot [Lite]" },
    { 317, "Javelin Shot" },
    { 318, "Knuckle Shot [Lite]" },
    { 320, "Analyze Shot [Lite]" },
    { 321, "Crash Shot" },
    { 322, "Needle Shot [Lite]" },
    { 323, "Sandstorm Shot [Lite]" },
    { 324, "Wild Shot [Lite]" },
    { 325, "Trick Shot [Lite]" },
    { 327, "Bomber Shot" },
    { 339, "Sharpness Shot [Lite]" },
    { 900, "Bullet Shot" },
    { 901, "Power Shot" },
    { 902, "Megaton Shot" },
    { 903, "Buster Shot" },
    { 904, "Speed Shot" },
    { 905, "High-Speed Shot" },
    { 906, "Boost Shot" },
    { 907, "Sonic Shot" },
    { 908, "Precision Shot" },
    { 909, "Banana Shot" },
    { 910, "Control Shot" },
    { 911, "Edge Shot" },
};
static const int g_shotMoves_count = 75;

static const MoveEntry g_airshotMoves[] = {
    { 1000, "Crystal Overhead" },
    { 1001, "Flying Knee Shot" },
    { 1002, "Rolling Overhead Kick" },
    { 1003, "Flip Shot" },
    { 1004, "Aggressive Header" },
    { 1005, "Flying Trick Shot" },
    { 1006, "Rovesciata" },
    { 1007, "Warhead Header" },
    { 1008, "Tempest" },
    { 1009, "Quartz Overhead" },
    { 1010, "Docking Shot" },
    { 1011, "Sealing Overhead" },
    { 1012, "Long Dive Header" },
    { 1013, "Mysterious Bird Header" },
    { 1300, "Crystal Overhead [Lite]" },
    { 1301, "Flying Knee Shot [Lite]" },
    { 1302, "Rolling Overhead Kick [Lite]" },
    { 1303, "Flip Shot [Lite]" },
    { 1304, "Aggressive Header [Lite]" },
    { 1305, "Flying Trick Shot [Lite]" },
    { 1306, "Somersault Overhead" },
    { 1406, "Tope Con Giro Shot" },
    { 1309, "Quartz Overhead [Lite]" },
    { 1900, "Jumping Volley" },
    { 1901, "Powerful Header" },
    { 1902, "Overhead Shot" },
    { 1903, "Jumping Impact" },
    { 1904, "Full Power Header" },
    { 1905, "Jumping Overhead" },
    { 1906, "Aerial Volley" },
    { 1907, "Diving Header" },
};
static const int g_airshotMoves_count = 31;

static const MoveEntry g_savingMoves[] = {
    { 0, "Great Save" },
    { 1, "Wakado Style Save" },
    { 2, "Gutsy Save" },
    { 3, "Iron Save" },
    { 4, "Golden Save" },
    { 5, "Fantastic Save" },
    { 6, "Street Save" },
    { 7, "Hungry Save" },
    { 8, "Naniwa Dynamic Save" },
    { 9, "Endeavor Save" },
    { 10, "Kung Fu Save" },
    { 11, "Far Grab Save" },
    { 12, "Reinforced Save" },
    { 900, "Tough-as-Nails Save" },
    { 901, "Confident Save" },
};
static const int g_savingMoves_count = 15;

static const MoveEntry g_miracleMoves[] = {
    { 0, "Super Great Save" },
    { 1, "Triangle Kick Defense" },
    { 2, "All or Nothing" },
    { 3, "Stone Crusher" },
    { 4, "Golden Right Hand" },
    { 5, "Redemoinho" },
    { 6, "Max Raptor Fang" },
    { 7, "Miracle Commander" },
    { 8, "Naniwa Gutsy Save" },
    { 9, "Genius Save" },
    { 10, "Cinematic Kick" },
    { 11, "SGGK" },
    { 12, "Wakado Style Karate Punch Defense" },
    { 13, "Meteor Crash" },
    { 14, "Shining Golden Right Hand" },
    { 300, "Strong Heart Save" },
    { 305, "Super Great Save [Lite]" },
    { 302, "Brave Dive" },
    { 303, "Megaton Catch" },
    { 306, "Stone Crusher [Lite]" },
    { 304, "Gutsy Arm" },
    { 307, "Golden Right Hand [Lite]" },
    { 900, "Desperate Save" },
    { 901, "Force Save" },
};
static const int g_miracleMoves_count = 24;