// Auto-generated from editor_data.json - DO NOT EDIT BY HAND.
// Regenerate from the save editor's move database if it's updated.
#pragma once
struct MoveEntry { int id; const char* name; };

static const MoveEntry g_dribbleMoves[] = {
    { 0, "Heel Lift" },
    { 1, "South American Dribble" },
    { 2, "Straight Line Dribble" },
    { 3, "Forced Feint" },
    { 4, "Delicate Touch" },
    { 5, "Feinting Dribble" },
    { 6, "Wild Eagle Dribble" },
    { 7, "Magnificent Dribble" },
    { 8, "Rolling Dribble" },
    { 9, "Flying Squirrel Jump" },
    { 10, "Monkey Guard" },
    { 11, "Falcon Dribble" },
    { 12, "Low Falcon Dribble" },
    { 13, "Dump Truck Dribble" },
    { 14, "Acrobatic Dribble" },
    { 15, "Kaiser Dribble" },
    { 16, "Hedgehog Dribble" },
    { 17, "Magic Jump" },
    { 18, "Étoile Roulette" },
    { 19, "Beautiful Step" },
    { 20, "Kluivoort Turn" },
    { 21, "Crown Lifting" },
    { 22, "Santana Turn" },
    { 23, "Forward Somersault Dribble" },
    { 24, "High-Speed South American Dribble" },
    { 25, "Senghor Dance" },
    { 26, "Flores Dribble" },
    { 27, "Blake Dribble" },
    { 28, "Aurora Feint" },
    { 29, "Mirage Chapeau" },
    { 30, "Dynamic Feint" },
    { 31, "Muay Thai Dribble" },
    { 32, "Jumping Knee" },
    { 33, "Overhead Lift" },
    { 34, "Right-Angle Feint" },
    { 35, "Splendid Step" },
    { 36, "Leo Feint" },
    { 37, "Back Friends" },
    { 38, "Changeup Dribble" },
    { 39, "Panther Accel" },
    { 40, "Under Step" },
    { 41, "Fake Under" },
    { 42, "Rolling Chapeau" },
    { 43, "Low-Altitude Lift" },
    { 44, "Heavy Tank Dribble" },
    { 45, "Return Leg" },
    { 46, "Spring Step" },
    { 47, "Secret Passage" },
    { 48, "Roulette Spin" },
    { 49, "Spear Dribble" },
    { 50, "Carry Step" },
    { 300, "Heel Lift [Lite]" },
    { 301, "South American Dribble [Lite]" },
    { 302, "Straight Line Dribble [Lite]" },
    { 304, "Delicate Touch [Lite]" },
    { 306, "Wild Eagle Dribble [Lite]" },
    { 307, "Magnificent Dribble [Lite]" },
    { 311, "Sonic Dribble" },
    { 312, "Up-Tempo Dance" },
    { 313, "Powerful Push" },
    { 314, "Acrobatic Dribble [Lite]" },
    { 315, "Assault Dribble" },
    { 316, "Stoop Dribble" },
    { 317, "Spin Light Jump" },
    { 318, "Étoile Roulette [Lite]" },
    { 319, "Beautiful Step [Lite]" },
    { 320, "Great Fake" },
    { 321, "Trick Lifting" },
    { 348, "Swindler's Lifting" },
    { 322, "Muay Thai Dribble [Lite]" },
    { 323, "Forward Somersault Dribble [Lite]" },
    { 324, "High-Speed South American Dribble [Lite]" },
    { 325, "Up-Tempo Dance [Lite]" },
    { 326, "Flores Dribble [Lite]" },
    { 327, "Smash Dribble" },
    { 329, "Mirage Chapeau [Lite]" },
    { 330, "Dynamic Feint [Lite]" },
    { 332, "Jumping Knee [Lite]" },
    { 347, "Secret Passage [Lite]" },
    { 900, "Accel Dribble" },
    { 901, "Aerial Dribble" },
    { 902, "High-Speed Dribble" },
    { 903, "Fake Kick" },
    { 904, "Gear Change" },
    { 905, "Double Touch" },
    { 906, "Power Dribble" },
    { 907, "Megaton Dribble" },
    { 908, "Buster Dribble" },
    { 909, "Back Road" },
    { 910, "Step Over" },
    { 911, "Shield Bash" },
    { 912, "Matador Trick" },
};
static const int g_dribbleMoves_count = 92;

static const MoveEntry g_tackleMoves[] = {
    { 0, "Feinting Tackle" },
    { 1, "Power Defense" },
    { 2, "Razor Tackle" },
    { 3, "Shark Tackle" },
    { 4, "Kaiser Charge" },
    { 5, "Hedgehog Charge" },
    { 6, "Arrow Tackle" },
    { 7, "Upper Tackle" },
    { 8, "Spear Tackle" },
    { 9, "Solid Tackle" },
    { 10, "Cross Sliding" },
    { 11, "Double Leg Tackle" },
    { 12, "Screen Cut" },
    { 13, "Emperor's Cut" },
    { 14, "Blake Tackle" },
    { 15, "Aurora Curtain" },
    { 16, "Junguang Sliding" },
    { 17, "Rainbow Tackle" },
    { 18, "Muay Thai Tackle" },
    { 19, "Push Steal" },
    { 20, "Right-Angle Defense" },
    { 21, "Up-Tempo Cut" },
    { 22, "Open Charge" },
    { 23, "Biting Tackle" },
    { 24, "Arm Banker" },
    { 25, "Cool Steal" },
    { 26, "Muay Thai Sweep" },
    { 27, "Shadow Steal" },
    { 28, "Danger Spin" },
    { 29, "Sliding Header" },
    { 30, "Roll Sweeper" },
    { 31, "Sharp Steal" },
    { 301, "Power Defense [Lite]" },
    { 302, "Sharpness Cut" },
    { 303, "Brave Tackle" },
    { 304, "Riser Charge" },
    { 305, "Squat Charge" },
    { 306, "Arrow Tackle [Lite]" },
    { 307, "Upper Tackle [Lite]" },
    { 309, "Solid Tackle [Lite]" },
    { 310, "Cross Sliding [Lite]" },
    { 312, "Screen Cut [Lite]" },
    { 313, "Emperor's Cut [Lite]" },
    { 314, "Blow Tackle" },
    { 316, "Junguang Sliding [Lite]" },
    { 317, "Rainbow Tackle [Lite]" },
    { 318, "Combat Tackle" },
    { 322, "Open Charge [Lite]" },
    { 900, "Shoulder Charge" },
    { 901, "Powerful Charge" },
    { 902, "High-Speed Shoulder Charge" },
    { 903, "Hyper Charge" },
    { 904, "Paralyze Charge" },
    { 905, "Sliding" },
    { 906, "Sharp Sliding" },
    { 907, "Skillful Sliding" },
    { 908, "Forced Tackle" },
    { 909, "Desperate Sliding" },
    { 910, "Full Body Tackle" },
    { 911, "Raging Wave Tackle" },
    { 912, "Scythe Cut" },
    { 913, "Spinning Cut" },
    { 914, "Megaton Tackle" },
};
static const int g_tackleMoves_count = 63;

static const MoveEntry g_shotMoves[] = {
    { 0, "Drive Shot" },
    { 1, "Tiger Shot" },
    { 2, "Picturesque Shot" },
    { 3, "Eagle Shot" },
    { 4, "Slice Shot" },
    { 5, "Falcon Shot" },
    { 6, "Razor Shot" },
    { 7, "Fire Shot" },
    { 8, "Hedgehog Shot" },
    { 9, "Magic Shot" },
    { 10, "Slider Shot" },
    { 11, "Cannon Shot" },
    { 12, "Stinger Shot" },
    { 13, "Accel Shot" },
    { 14, "Sagittarius Shot" },
    { 15, "Sacred Shot" },
    { 16, "Diaz-Style Drive Shot" },
    { 17, "Panther Shot" },
    { 18, "Knuckle Shot" },
    { 19, "Vulture Shot" },
    { 20, "Analyze Shot" },
    { 21, "Blake Shot" },
    { 22, "Needle Shot" },
    { 23, "Sandstorm Shot" },
    { 24, "Wild Shot" },
    { 25, "Trick Shot" },
    { 27, "Dragon Shot" },
    { 28, "Acrobatic Hoop" },
    { 29, "Blast Force" },
    { 30, "Windfall" },
    { 31, "Biting Shot" },
    { 32, "Fake Shot" },
    { 33, "Sand Mirage Shot" },
    { 34, "Vulcan Cannon" },
    { 35, "Vanishing Shot" },
    { 36, "Panzer Shot" },
    { 37, "Sunset Shot" },
    { 38, "Radiant Shot" },
    { 41, "Rock Blaster" },
    { 300, "Drive Shot [Lite]" },
    { 301, "Tiger Shot [Lite]" },
    { 302, "Picturesque Shot [Lite]" },
    { 303, "Field Shot" },
    { 304, "Slice Shot [Lite]" },
    { 306, "Spinning Shot" },
    { 307, "Fire Shot [Lite]" },
    { 310, "Slider Shot [Lite]" },
    { 353, "Cannon Shot [Lite]" },
    { 311, "Rising Bazooka" },
    { 313, "Accel Shot [Lite]" },
    { 314, "Sagittarius Shot [Lite]" },
    { 315, "Sacred Shot [Lite]" },
    { 316, "Diaz-Style Drive Shot [Lite]" },
    { 317, "Javelin Shot" },
    { 318, "Knuckle Shot [Lite]" },
    { 320, "Analyze Shot [Lite]" },
    { 321, "Crash Shot" },
    { 322, "Needle Shot [Lite]" },
    { 323, "Sandstorm Shot [Lite]" },
    { 324, "Wild Shot [Lite]" },
    { 325, "Trick Shot [Lite]" },
    { 327, "Bomber Shot" },
    { 339, "Sharpness Shot [Lite]" },
    { 900, "Bullet Shot" },
    { 901, "Power Shot" },
    { 902, "Megaton Shot" },
    { 903, "Buster Shot" },
    { 904, "Speed Shot" },
    { 905, "High-Speed Shot" },
    { 906, "Boost Shot" },
    { 907, "Sonic Shot" },
    { 908, "Precision Shot" },
    { 909, "Banana Shot" },
    { 910, "Control Shot" },
    { 911, "Edge Shot" },
};
static const int g_shotMoves_count = 75;

static const MoveEntry g_airshotMoves[] = {
    { 1000, "Crystal Overhead" },
    { 1001, "Flying Knee Shot" },
    { 1002, "Rolling Overhead Kick" },
    { 1003, "Flip Shot" },
    { 1004, "Aggressive Header" },
    { 1005, "Flying Trick Shot" },
    { 1006, "Rovesciata" },
    { 1007, "Warhead Header" },
    { 1008, "Tempest" },
    { 1009, "Quartz Overhead" },
    { 1010, "Docking Shot" },
    { 1011, "Sealing Overhead" },
    { 1012, "Long Dive Header" },
    { 1013, "Mysterious Bird Header" },
    { 1300, "Crystal Overhead [Lite]" },
    { 1301, "Flying Knee Shot [Lite]" },
    { 1302, "Rolling Overhead Kick [Lite]" },
    { 1303, "Flip Shot [Lite]" },
    { 1304, "Aggressive Header [Lite]" },
    { 1305, "Flying Trick Shot [Lite]" },
    { 1306, "Somersault Overhead" },
    { 1406, "Tope Con Giro Shot" },
    { 1309, "Quartz Overhead [Lite]" },
    { 1900, "Jumping Volley" },
    { 1901, "Powerful Header" },
    { 1902, "Overhead Shot" },
    { 1903, "Jumping Impact" },
    { 1904, "Full Power Header" },
    { 1905, "Jumping Overhead" },
    { 1906, "Aerial Volley" },
    { 1907, "Diving Header" },
};
static const int g_airshotMoves_count = 31;

static const MoveEntry g_savingMoves[] = {
    { 0, "Great Save" },
    { 1, "Wakado Style Save" },
    { 2, "Gutsy Save" },
    { 3, "Iron Save" },
    { 4, "Golden Save" },
    { 5, "Fantastic Save" },
    { 6, "Street Save" },
    { 7, "Hungry Save" },
    { 8, "Naniwa Dynamic Save" },
    { 9, "Endeavor Save" },
    { 10, "Kung Fu Save" },
    { 11, "Far Grab Save" },
    { 12, "Reinforced Save" },
    { 900, "Tough-as-Nails Save" },
    { 901, "Confident Save" },
};
static const int g_savingMoves_count = 15;

static const MoveEntry g_miracleMoves[] = {
    { 0, "Super Great Save" },
    { 1, "Triangle Kick Defense" },
    { 2, "All or Nothing" },
    { 3, "Stone Crusher" },
    { 4, "Golden Right Hand" },
    { 5, "Redemoinho" },
    { 6, "Max Raptor Fang" },
    { 7, "Miracle Commander" },
    { 8, "Naniwa Gutsy Save" },
    { 9, "Genius Save" },
    { 10, "Cinematic Kick" },
    { 11, "SGGK" },
    { 12, "Wakado Style Karate Punch Defense" },
    { 13, "Meteor Crash" },
    { 14, "Shining Golden Right Hand" },
    { 300, "Strong Heart Save" },
    { 305, "Super Great Save [Lite]" },
    { 302, "Brave Dive" },
    { 303, "Megaton Catch" },
    { 306, "Stone Crusher [Lite]" },
    { 304, "Gutsy Arm" },
    { 307, "Golden Right Hand [Lite]" },
    { 900, "Desperate Save" },
    { 901, "Force Save" },
};
static const int g_miracleMoves_count = 24;

// Super Move catalog (name + catalog type string, for reference only -
// the live SuperType BYTE this maps to is NOT yet confirmed, see README).
struct SuperMoveEntry { int id; const char* name; const char* type; };
static const SuperMoveEntry g_superMoves[] = {
    { 1000, "Summon Raiju Shot", "SHOOT" },
    { 1001, "Blue-Sky Falcon Fall", "SHOOT" },
    { 1002, "Blast Bomber", "SHOOT" },
    { 1102, "Mysterious Bird Dance", "SHOOT" },
    { 1003, "Diving Vulture", "SHOOT" },
    { 1004, "Double-Speed Double-Spin Midair Tornado", "SHOOT" },
    { 1005, "Crystal Drop", "SHOOT" },
    { 1006, "Eclipse", "SHOOT" },
    { 1007, "Rising Phoenix", "SHOOT" },
    { 1900, "Sky Volley", "SHOOT" },
    { 1901, "Sonic Header", "SHOOT" },
    { 1902, "Precise Overhead", "SHOOT" },
    { 1000, "Toho Twin Shot", "COOPERATION_SHOOT" },
    { 1001, "Skylab Twin Shot", "COOPERATION_SHOOT" },
    { 1002, "Skylab Hurricane", "COOPERATION_SHOOT" },
    { 1003, "Sunfall Big Bang", "COOPERATION_SHOOT" },
    { 1004, "Skylab Triangle", "COOPERATION_SHOOT" },
    { 0, "Overhead Block", "BLOCK" },
    { 1, "Face Block", "BLOCK" },
    { 2, "Super Reflex Block", "BLOCK" },
    { 3, "Rhythmic Block", "BLOCK" },
    { 4, "Superspeed Kickback Cannon", "BLOCK" },
    { 5, "Red Stopper", "BLOCK" },
    { 6, "Big Gun Block", "BLOCK" },
    { 7, "Soldier Block", "BLOCK" },
    { 304, "Superspeed Kickback Cannon [Lite]", "BLOCK" },
    { 900, "Sidekick Block", "BLOCK" },
    { 901, "Jumping Body Block", "BLOCK" },
    { 902, "Sliding Block", "BLOCK" },
    { 0, "Crystal Accel", "DRIBBLE" },
    { 1, "High Magic Dance", "DRIBBLE" },
    { 2, "Scissor Roulette", "DRIBBLE" },
    { 3, "Crown Dance", "DRIBBLE" },
    { 4, "Miracle Acrobat", "DRIBBLE" },
    { 5, "Lightspeed Right-Angle Feint", "DRIBBLE" },
    { 6, "Rough Stepper", "DRIBBLE" },
    { 306, "Double Shutter", "DRIBBLE" },
    { 7, "Triple Spin", "DRIBBLE" },
    { 8, "Slide Diver", "DRIBBLE" },
    { 302, "Technical Scissor", "DRIBBLE" },
    { 402, "Scissor Roulette [Lite]", "DRIBBLE" },
    { 900, "Powerful Rush", "DRIBBLE" },
    { 901, "Dash Fake", "DRIBBLE" },
    { 0, "Boomerang Booster", "PASS" },
    { 1, "Eagle Heart Pass", "PASS" },
    { 2, "Hedgehog Pass", "PASS" },
    { 3, "Heavy Arrow Pass", "PASS" },
    { 4, "Compact Thread", "PASS" },
    { 5, "Step Gift", "PASS" },
    { 6, "Arc Bridge Gift", "PASS" },
    { 7, "Conductor Pass", "PASS" },
    { 8, "Orbital Curve", "PASS" },
    { 9, "Fang Roll Pass", "PASS" },
    { 10, "Chaser Pass", "PASS" },
    { 11, "Irregularity Snipe", "PASS" },
    { 12, "Sunset Up", "PASS" },
    { 13, "Twister Pass", "PASS" },
    { 14, "Gale Pass", "PASS" },
    { 15, "Sunrise Pass", "PASS" },
    { 304, "Cool Lead", "PASS" },
    { 305, "Trust Pass", "PASS" },
    { 900, "Buster Pass", "PASS" },
    { 901, "Rocket Pass", "PASS" },
    { 902, "Spinning Pass", "PASS" },
    { 0, "Flying Drive Shot", "SHOOT" },
    { 1, "Neo Drive Shot", "SHOOT" },
    { 2, "Miracle Drive Shot", "SHOOT" },
    { 3, "Raiju Shot", "SHOOT" },
    { 4, "Neo Tiger Shot", "SHOOT" },
    { 5, "Wild Eagle Shot", "SHOOT" },
    { 6, "Sky Rocket Volley", "SHOOT" },
    { 7, "Neo Fire Shot", "SHOOT" },
    { 8, "High Fire Shot", "SHOOT" },
    { 9, "Heavenly Shot", "SHOOT" },
    { 10, "Dual Slider Shot", "SHOOT" },
    { 11, "Vendémiaire Cannon", "SHOOT" },
    { 12, "Spiral Stinger", "SHOOT" },
    { 13, "High Stinger Shot", "SHOOT" },
    { 14, "Curtain Call Shot", "SHOOT" },
    { 15, "Golden Arrow", "SHOOT" },
    { 16, "Miracle Overhead", "SHOOT" },
    { 17, "Miracle Bound", "SHOOT" },
    { 18, "Jet Panther Shot", "SHOOT" },
    { 19, "Arc Bridge Shot", "SHOOT" },
    { 20, "Rabona Illusion", "SHOOT" },
    { 21, "Levin Shot: Revolve", "SHOOT" },
    { 22, "Bright Sharpness", "SHOOT" },
    { 23, "Hi-Dragon Shot", "SHOOT" },
    { 24, "Lifting Circus", "SHOOT" },
    { 25, "Super Vulcan Cannon", "SHOOT" },
    { 26, "Double Sunset Shot", "SHOOT" },
    { 27, "Great Rock Blaster", "SHOOT" },
    { 28, "Hyper Blake Shot", "SHOOT" },
    { 29, "Drachen Doppel", "SHOOT" },
    { 30, "Schwere Panzer", "SHOOT" },
    { 31, "Spadille Shot", "SHOOT" },
    { 31, "Joker Smash", "SHOOT" },
    { 33, "Tornado Shot", "SHOOT" },
    { 305, "Wild Eagle Shot [Lite]", "SHOOT" },
    { 311, "Detonation Impact", "SHOOT" },
    { 316, "Miracle Overhead [Lite]", "SHOOT" },
    { 320, "Rabona Illusion [Lite]", "SHOOT" },
    { 324, "Lifting Circus [Lite]", "SHOOT" },
    { 950, "Mighty Shot [Lite]", "SHOOT" },
    { 900, "Mighty Shot", "SHOOT" },
    { 901, "Rapid Shot", "SHOOT" },
    { 902, "Edge Slicer Shot", "SHOOT" },
    { 0, "All Japan Twin Shot", "COOPERATION_SHOOT" },
    { 1, "Neo Drive Tiger Twin Shot", "COOPERATION_SHOOT" },
    { 2, "Twin Shot", "COOPERATION_SHOOT" },
    { 3, "Lumiere Ricochet", "COOPERATION_SHOOT" },
    { 4, "Double Force Shot", "COOPERATION_SHOOT" },
    { 5, "Justice Blake Shot", "COOPERATION_SHOOT" },
    { 6, "Twin Mirage", "COOPERATION_SHOOT" },
    { 7, "Konsawatt Combination", "COOPERATION_SHOOT" },
    { 8, "Fire Twin Shot", "COOPERATION_SHOOT" },
    { 9, "Flash Raiju Shot", "COOPERATION_SHOOT" },
    { 10, "Argentina Twin Shot", "COOPERATION_SHOOT" },
    { 11, "Brazilian Twin Shot", "COOPERATION_SHOOT" },
    { 0, "Dump Roller", "TACKLE" },
    { 1, "Razor Slider", "TACKLE" },
    { 2, "Cutting Shield", "TACKLE" },
    { 3, "Sacred Chaser", "TACKLE" },
    { 4, "Ten Kao Strike", "TACKLE" },
    { 5, "Cut Out Steal", "TACKLE" },
    { 6, "Elbow Charge", "TACKLE" },
    { 7, "Guillotine Slide", "TACKLE" },
    { 303, "Sacred Chaser [Lite]", "TACKLE" },
    { 950, "Power Slide [Lite]", "TACKLE" },
    { 900, "Power Slide", "TACKLE" },
    { 901, "Diving Steal", "TACKLE" },
};
static const int g_superMoves_count = 131;
// CharaID -> display name (for the array-dump tool)
struct PlayerNameEntry { int chara_id; const char* name; };
static const PlayerNameEntry g_playerNames[] = {
    { 1, "Tsubasa" },
    { 2, "Hyuga" },
    { 3, "Genzo" },
    { 4, "Misaki" },
    { 5, "Matsuyama" },
    { 6, "Misugi" },
    { 7, "Masao T" },
    { 8, "Kazuo T" },
    { 9, "Nitta" },
    { 10, "Jito" },
    { 11, "Soda" },
    { 12, "Ishizaki" },
    { 13, "Ken" },
    { 14, "MoriGOD" },
    { 15, "Takasugi" },
    { 16, "Izawa" },
    { 17, "Sawada" },
    { 18, "Sano" },
    { 19, "Taki" },
    { 20, "Sorimachi" },
    { 21, "Kisugi" },
    { 22, "Urabe" },
    { 23, "Kishida" },
    { 24, "Nakayama" },
    { 25, "Nishio" },
    { 26, "Oda" },
    { 27, "Honma" },
    { 30, "Sawaki" },
    { 31, "Ishida" },
    { 32, "K.H. Scheneider" },
    { 33, "Kaltz" },
    { 34, "Schester" },
    { 35, "Margus" },
    { 36, "Muller" },
    { 37, "Heine" },
    { 38, "Pierre" },
    { 39, "Napoleon" },
    { 40, "Jean" },
    { 41, "Kluivoort" },
    { 42, "Klismann" },
    { 43, "Kaiser" },
    { 44, "Lensenblink" },
    { 45, "Dirk" },
    { 46, "Doleman" },
    { 47, "Gino Hernandez" },
    { 48, "Rusciano" },
    { 49, "Robson" },
    { 50, "Santana" },
    { 51, "Luciano Leo" },
    { 52, "Alberto" },
    { 53, "Keizinho" },
    { 54, "Juan Diaz" },
    { 55, "Pascal" },
    { 56, "Galvan" },
    { 57, "Ramon Victorino" },
    { 58, "Senghor" },
    { 59, "M.M. Diallo" },
    { 60, "Ryan Ortiz" },
    { 61, "Blake Martin" },
    { 62, "Azwan" },
    { 63, "Stefan Levin" },
    { 64, "Xiao" },
    { 65, "Owairan" },
    { 66, "Pepe" },
    { 67, "Bunnak" },
    { 68, "Ricardo Espadas" },
    { 69, "Ryoma Hino" },
    { 70, "Shingo" },
    { 71, "Nakanishi" },
    { 72, "Akai" },
    { 73, "Teigerbran" },
    { 74, "Felix Blanc" },
    { 75, "Malder" },
    { 76, "Gentile" },
    { 77, "Finn" },
    { 78, "Salinas" },
    { 79, "Natureza" },
    { 80, "Victor" },
    { 81, "Luna" },
    { 82, "Nico Castillo" },
    { 83, "Brolin" },
    { 84, "Larsson" },
    { 85, "Frederiks" },
    { 86, "Wu" },
    { 87, "Fei" },
    { 88, "Wang" },
    { 89, "Yuan" },
    { 90, "Vulcan" },
    { 91, "Khalid" },
    { 92, "Faran" },
    { 93, "Sukun" },
    { 94, "Chana" },
    { 95, "Patara" },
    { 96, "Garcia" },
    { 97, "Arbez" },
    { 98, "Lopez" },
    { 99, "Suarez" },
    { 100, "Zaragoza" },
    { 101, "Estrada" },
    { 102, "Raymond Chandler" },
    { 103, "Bouba Milla" },
    { 104, "Zangief" },
    { 105, "Lian Wincott" },
    { 106, "Nolan Stewart" },
    { 107, "Lee" },
    { 108, "Cha" },
    { 109, "Gil" },
    { 110, "Diack Wade" },
    { 111, "Caleb Ward" },
    { 112, "Gavin Bright" },
    { 113, "Conner Barnard" },
    { 114, "Tanner Barnard" },
    { 115, "Eko Jawato" },
    { 116, "Emilio Romero" },
    { 117, "Abel Romero" },
    { 120, "Keizinho (GK)" },
    { 1008, "Furuta" },
    { 1010, "Imai" },
    { 1012, "Koike" },
    { 1013, "Matsuki" },
    { 1045, "Noda" },
    { 1051, "Himeji" },
    { 1061, "Daimaru" },
    { 1083, "Takizawa" },
    { 1122, "Hardwich" },
    { 1123, "Mayer" },
    { 1124, "Magath" },
    { 1126, "Max" },
    { 1130, "Amoros" },
    { 1132, "Rust" },
    { 1133, "Ferreri" },
    { 1134, "Bravo" },
    { 1137, "Bossis" },
    { 1140, "Belmondo" },
    { 1142, "Hahn" },
    { 1143, "Kolff" },
    { 1144, "Fillip" },
    { 1157, "Conti" },
    { 1159, "Tardelli" },
    { 1164, "Robinson" },
    { 1165, "Dean" },
    { 1166, "Wright" },
    { 1183, "Lucas" },
    { 1189, "Galtoni" },
    { 1190, "Sembero" },
    { 1191, "Pasaro" },
    { 1193, "Ruggeri" },
    { 1194, "Jeites" },
    { 1195, "Palus" },
    { 1196, "Brown" },
    { 1215, "Admed" },
    { 1216, "Diara" },
    { 1217, "Sow" },
    { 1218, "Seye" },
    { 1220, "Mbengue" },
    { 1221, "Faye" },
    { 1222, "Camara" },
    { 1223, "Seck" },
    { 1228, "Stone GOAT" },
    { 1230, "William" },
    { 1315, "Amamiya" },
    { 1316, "Ohashi" },
    { 1317, "Igarashi" },
    { 1320, "Sasaki" },
    { 1321, "Yamane" },
    { 1322, "Fukuma" },
    { 1323, "Yoshioka" },
    { 1324, "Tsuda" },
    { 1325, "Kanesaka" },
    { 1326, "Tanabe" },
    { 1327, "Tateishi" },
    { 1328, "Matsumura" },
    { 1329, "Tsukimori" },
    { 1330, "Haseyama" },
    { 1331, "Kakizaki" },
    { 1332, "Kodama" },
    { 1333, "Hakadama" },
    { 1334, "Yuzawa" },
    { 1335, "Hiroaki" },
    { 1336, "Takashina" },
    { 1340, "Yonekura" },
    { 1341, "Arikawa" },
    { 1342, "Hirose" },
    { 1343, "Takayanagi" },
    { 1344, "Tabuchi" },
    { 1345, "Kawakubo" },
    { 1346, "Vinicius" },
    { 1347, "Raul" },
    { 1348, "Joaquim" },
    { 1349, "Nunes" },
    { 1350, "Vieira" },
    { 1351, "Duarte" },
    { 1352, "Caio" },
    { 1353, "Machado" },
    { 1354, "Arthur" },
    { 1355, "Lima" },
    { 1356, "Milton" },
    { 1357, "Jose" },
    { 1358, "Sergio" },
    { 1359, "Anthoine" },
    { 1360, "Sandro" },
    { 1361, "Guilherme" },
    { 1362, "Nascimento" },
    { 1363, "Leandro" },
    { 1364, "Jorginho" },
    { 1365, "Douglas" },
    { 1366, "Andrade" },
    { 1367, "Gustavo" },
    { 1368, "Nelson" },
    { 1369, "Ferreira" },
    { 1370, "Campos" },
    { 1371, "Goncalves" },
    { 1372, "Igor" },
    { 1373, "Marinho" },
    { 1374, "Vargas" },
    { 1375, "Carrizo" },
    { 1376, "Quiroga" },
    { 1377, "Rojas" },
    { 1378, "Sosa" },
    { 1379, "Ponce" },
    { 1380, "Ezequiel" },
    { 1381, "Acosta" },
    { 1382, "Herrera" },
    { 1383, "Casa Grande" },
    { 1384, "Abilio" },
    { 1385, "Breno" },
    { 1386, "Ramos" },
    { 1387, "Anderson" },
    { 1388, "Freitas" },
    { 1389, "Tarso" },
    { 1390, "Pereira" },
    { 1391, "Gilberto" },
    { 1392, "Klaus" },
    { 1393, "Constantin" },
    { 1394, "Benedict" },
    { 1395, "Eno" },
    { 1396, "Reinhard" },
    { 1397, "Warner" },
    { 1398, "Lars" },
    { 1399, "Gustav" },
    { 1400, "Ernst" },
    { 1401, "Maurice" },
    { 1402, "Fredrik" },
    { 1403, "Galante" },
    { 1404, "Tacchinardi" },
    { 1405, "Pagot" },
    { 1406, "Blanca" },
    { 1407, "Delvecchio" },
    { 1408, "Panuzzi" },
    { 1409, "Percy" },
    { 1410, "Howard" },
    { 1411, "Kyle" },
    { 1412, "Rufus" },
    { 1413, "Jaden" },
    { 1414, "Gary" },
    { 1415, "Dugo" },
    { 1416, "Melo" },
    { 1417, "Conzalez" },
    { 1418, "Pazu" },
    { 1419, "Olivares" },
    { 1420, "Amerigo" },
    { 1421, "Fillippo" },
    { 1422, "Dionisi" },
    { 1423, "Fengas" },
    { 1424, "Enrico" },
    { 1425, "Garelli" },
    { 1426, "Mild" },
    { 1427, "Tomah" },
    { 1428, "Nilsson" },
    { 1429, "Lane" },
    { 1430, "Ljung" },
    { 1431, "Ravelli" },
    { 1432, "Cao" },
    { 1433, "Gao" },
    { 1434, "Fan" },
    { 1435, "Xie" },
    { 1436, "Hu" },
    { 1437, "Peng" },
    { 1438, "Deayea" },
    { 1439, "Fatia" },
    { 1440, "Amdin" },
    { 1441, "Rasheed" },
    { 1442, "Halal" },
    { 1443, "Jahal" },
    { 1444, "Ibn" },
    { 1445, "Louay" },
    { 1446, "Wachalabon" },
    { 1447, "Chuwattana" },
    { 1448, "Napa" },
    { 1449, "Sommrit" },
    { 1450, "Chalermesi" },
    { 1451, "Tawan" },
    { 1452, "Medina" },
    { 1453, "Gomez" },
    { 1454, "Carvajal" },
    { 1455, "Espino" },
    { 1456, "Sadjo" },
    { 1457, "Atangana" },
    { 1458, "Nana" },
    { 1459, "Kamgaing" },
    { 1460, "Kene" },
    { 1461, "Bellingha" },
    { 1462, "Hamadou" },
    { 1463, "Yaoba" },
    { 1464, "Ahidjo" },
    { 1465, "Krestow" },
    { 1466, "Radchenko" },
    { 1467, "Nazarov" },
    { 1468, "Ruzinov" },
    { 1469, "Jekin" },
    { 1470, "Salenko" },
    { 1471, "Guarin" },
    { 1472, "Tetradze" },
    { 1473, "Hallin" },
    { 1474, "Popov" },
    { 1475, "Yumikura" },
    { 1476, "Yoshikawa" },
    { 1477, "Okano" },
    { 1478, "Sakaki" },
    { 1479, "Yamada" },
    { 1484, "Grayson" },
    { 1488, "Freddy" },
    { 1489, "Rendy" },
    { 1490, "Roni" },
    { 1491, "Hasan" },
    { 1492, "Ari" },
    { 1493, "Joe" },
    { 1494, "Anton" },
    { 1495, "Fariz" },
    { 1496, "Ricky" },
    { 1497, "Dede" },
    { 1498, "Dylan" },
    { 1499, "Carson" },
    { 1500, "Henry" },
    { 1501, "Thomas" },
    { 1502, "Hunter" },
    { 1503, "Jarvis" },
    { 1504, "Ivan" },
    { 1505, "Briggs" },
    { 1506, "Hiram" },
    { 1507, "Melvin" },
    { 1508, "Hong" },
    { 1509, "Son" },
    { 1510, "Ki" },
    { 1511, "Kin" },
    { 1512, "Kou" },
    { 1513, "Chou" },
    { 1514, "Gu" },
    { 1515, "Park" },
    { 1516, "Ulises" },
    { 1517, "Pablo" },
    { 1518, "Quique" },
    { 1519, "Celso" },
    { 1520, "Eladio" },
    { 1521, "Francisco" },
    { 1522, "Jacinto" },
    { 1523, "Zacarias" },
    { 1524, "Tacito" },
};
static const int g_playerNames_count = 358;
